import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/context/app-context-";
import { headers } from "next/headers";
import { InitialDataType } from "@/types/types";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Centro Andaluz",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();

  const eventsData = headersList.get("x-backend-events");
  const categoriesData = headersList.get("x-backend-category");
  const menuData = headersList.get("x-backend-menu");

  const backendError = headersList.get("x-backend-error");
  const dataSource = headersList.get("x-data-source") || "api";
  const cacheHit = headersList.get("x-cache-hit") === "true";

  let initialData: InitialDataType = {
    events: null,
    categories: null,
    menus: null,
    metadata: {
      source: dataSource,
      cacheHit: cacheHit,
      fetchedAt: new Date().toISOString(),
      error: null as any,
    },
  };

  if (eventsData) {
    try {
      initialData.events = JSON.parse(eventsData);
    } catch (error) {
      console.error("Error parsing events data in layout:", error);
    }
  }

  if (categoriesData) {
    try {
      initialData.categories = JSON.parse(categoriesData);
    } catch (error) {
      console.error("Error parsing categories data in layout:", error);
    }
  }

  if (menuData) {
    try {
      initialData.menus = JSON.parse(menuData);
    } catch (error) {
      console.error("Error parsing menu data in layout:", error);
    }
  }

  if (backendError) {
    try {
      initialData.metadata.error = JSON.parse(backendError);
    } catch (error) {
      initialData.metadata.error = { message: "Unknown error" };
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background h-screen max-h-screen`}
      >
        <AppContextProvider
          initialEvents={initialData.events}
          initialCategories={initialData.categories}
          initialMenus={initialData.menus}
          initialMetadata={initialData.metadata}
        >
          <Header />
          {children}
          <Footer />
        </AppContextProvider>

        {process.env.NODE_ENV === "development" && (
          <div className="fixed bottom-4 right-4 bg-gray-900 text-white text-xs p-2 rounded-lg opacity-70 hover:opacity-100 transition-opacity z-50">
            <div className="flex items-center gap-2">
              <div
                className={`w-2 h-2 rounded-full ${
                  cacheHit ? "bg-green-500" : "bg-blue-500"
                }`}
              />
              <span>Data: {dataSource}</span>
              {initialData.events && (
                <span className="ml-2">
                  Events: {initialData.events.length}
                </span>
              )}
              {initialData.categories && (
                <span className="ml-2">
                  Categorys: {initialData.categories.length}
                </span>
              )}
              {initialData.menus && (
                <span className="ml-2">Menus: {initialData.menus.length}</span>
              )}
            </div>
          </div>
        )}
      </body>
    </html>
  );
}
